apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml

images:
  - name: pingcrm-app
    newName: ghcr.io/OWNER/pingcrm
    newTag: latest
  - name: pingcrm-ssr
    newName: ghcr.io/OWNER/pingcrm
    newTag: ssr

# Secrets are managed externally (CI/CD creates them via kubectl)
