apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pingcrm
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssr
  namespace: pingcrm
spec:
  replicas: 2
