apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pingcrm
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssr
  namespace: pingcrm
spec:
  template:
    spec:
      containers:
        - name: ssr
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
  namespace: pingcrm
spec:
  template:
    spec:
      containers:
        - name: horizon
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverb
  namespace: pingcrm
spec:
  template:
    spec:
      containers:
        - name: reverb
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
