# Production environment override
services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: test
    labels:
      - traefik.enable=true
      - traefik.http.routers.pingcrm.rule=Host(`${DOMAIN_NAME}`)
      - traefik.http.routers.pingcrm.entrypoints=websecure
      - traefik.http.routers.pingcrm.tls=true
