x-logging: &default-logging
  driver: 'json-file'
  options:
    max-size: "50m"
    max-file: 6
x-network: &default-network
  internal:
x-base: &base
  ulimits:
    nofile:
      soft: 20000
      hard: 40000
  logging: *default-logging

services:
  app:
    <<: *base
    command: ["php", "/var/www/html/artisan", "octane:start", "--server=frankenphp", "--port=8000"]
    stop_signal: SIGTERM
    environment:
      AUTORUN_LARAVEL_MIGRATION_MODE: "fresh"
      AUTORUN_LARAVEL_MIGRATION_SEED: "true"
      INERTIA_SSR_URL: "http://ssr:13714"
      INERTIA_SSR_ENSURE_BUNDLE_EXISTS: "false"
      HEALTHCHECK_PATH: "/up"
    networks:
      - internal
      - spin-network
    healthcheck:
      test: ["CMD", "healthcheck-octane"]
      start_period: 90s
      interval: 10s
      timeout: 10s
      retries: 3

  queue:
    <<: *base
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    stop_signal: SIGTERM
    networks: *default-network
    healthcheck:
      test: ["CMD", "healthcheck-queue"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 2

  scheduler:
    <<: *base
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    stop_signal: SIGTERM
    networks: *default-network
    healthcheck:
      test: ["CMD", "healthcheck-schedule"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 2

  reverb:
    <<: *base
    command: ["php", "/var/www/html/artisan", "reverb:start", "--port=8080"]
    stop_signal: SIGTERM
    networks:
      - internal
      - spin-network
    healthcheck:
      test: ["CMD", "healthcheck-reverb"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 2

  valkey:
    image: 'valkey/valkey:9-alpine@sha256:c9b77919daeba2c02ad954d0c844cc4e7142069d177b89c5fd771f405daf9e02'
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [ "valkey-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory", "2gb" ]
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    logging: *default-logging
    networks: *default-network
    healthcheck:
      test: [ "CMD", "valkey-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      retries: 3
      timeout: 5s

  postgres:
    image: postgres:18@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    networks: *default-network
    logging: *default-logging
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "${DB_DATABASE}" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  typesense:
    image: 'typesense/typesense:30.2@sha256:610f2d34b1f93d00762869da2c67736775e5798d19a2c8b91b014b8a0cc1e110'
    command: ["--data-dir=/data", "--api-key=${TYPESENSE_API_KEY}", "--enable-cors"]
    environment:
      TYPESENSE_API_KEY: "${TYPESENSE_API_KEY}"
    logging:
      driver: 'json-file'
      options:
        max-size: "50m"
        max-file: "6"
    networks: *default-network

networks:
  internal:
  spin-network:
    external: true
