#!/usr/bin/env sh

set -e

container_mode=${CONTAINER_MODE:-"http"}

check_supervisor_service() {
    service_name="$1"
    if [ "$(supervisorctl status "$service_name:${service_name}_0" | awk '{print tolower($2)}')" = "running" ]; then
        exit 0
    else
        echo "Healthcheck failed."
        exit 1
    fi
}

case "${container_mode}" in
    "http")
        php "${ROOT}/artisan" octane:status
        ;;
    "horizon"|"scheduler"|"reverb"|"worker")
        check_supervisor_service "${container_mode}"
        ;;
    *)
        echo "Container mode mismatched."
        exit 1
        ;;
esac
