#ddev-generated
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5172
    https_port: 5173

web_extra_daemons:
  - name: vite
    command: "cd ${DDEV_COMPOSER_ROOT} && ${JAVASCRIPT_PACKAGE_MANAGER} run dev"
    directory: /var/www/html

hooks:
  post-start:
    - exec: >
        if [ ! -d node_modules ]; then
          ${JAVASCRIPT_PACKAGE_MANAGER} install;
        fi
